# coding: utf-8

"""
    Kimai - API Docs

    JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json)   # noqa: E501

    OpenAPI spec version: 0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kimai_python
from kimai_python.models.id_meta_body3 import IdMetaBody3  # noqa: E501
from kimai_python.rest import ApiException


class TestIdMetaBody3(unittest.TestCase):
    """IdMetaBody3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdMetaBody3(self):
        """Test IdMetaBody3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kimai_python.models.id_meta_body3.IdMetaBody3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
