# coding: utf-8

"""
    Kimai - API Docs

    JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json)   # noqa: E501

    OpenAPI spec version: 0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kimai_python
from kimai_python.api.meta_field_api import MetaFieldApi  # noqa: E501
from kimai_python.rest import ApiException


class TestMetaFieldApi(unittest.TestCase):
    """MetaFieldApi unit test stubs"""

    def setUp(self):
        self.api = MetaFieldApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_metafields_get(self):
        """Test case for api_metafields_get

        Returns a collection of meta-fields  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
