# coding: utf-8

"""
    Kimai - API Docs

    JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json)   # noqa: E501

    OpenAPI spec version: 0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kimai_python
from kimai_python.models.customer import Customer  # noqa: E501
from kimai_python.rest import ApiException


class TestCustomer(unittest.TestCase):
    """Customer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomer(self):
        """Test Customer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kimai_python.models.customer.Customer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
