# coding: utf-8

"""
    Kimai - API Docs

    JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json)   # noqa: E501

    OpenAPI spec version: 0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kimai_python
from kimai_python.api.tag_api import TagApi  # noqa: E501
from kimai_python.rest import ApiException


class TestTagApi(unittest.TestCase):
    """TagApi unit test stubs"""

    def setUp(self):
        self.api = TagApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_tags_get(self):
        """Test case for api_tags_get

        Fetch all existing tags  # noqa: E501
        """
        pass

    def test_api_tags_id_delete(self):
        """Test case for api_tags_id_delete

        Delete a tag  # noqa: E501
        """
        pass

    def test_api_tags_post(self):
        """Test case for api_tags_post

        Creates a new tag  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
