# coding: utf-8

"""
    Kimai - API Docs

    JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json)   # noqa: E501

    OpenAPI spec version: 0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kimai_python
from kimai_python.api.task_api import TaskApi  # noqa: E501
from kimai_python.rest import ApiException


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self):
        self.api = TaskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_tasks_get(self):
        """Test case for api_tasks_get

        Returns a collection of tasks  # noqa: E501
        """
        pass

    def test_api_tasks_id_assign_patch(self):
        """Test case for api_tasks_id_assign_patch

        Assign a task to the current user  # noqa: E501
        """
        pass

    def test_api_tasks_id_close_patch(self):
        """Test case for api_tasks_id_close_patch

        Close a task for the current user  # noqa: E501
        """
        pass

    def test_api_tasks_id_delete(self):
        """Test case for api_tasks_id_delete

        Delete an existing task record  # noqa: E501
        """
        pass

    def test_api_tasks_id_get(self):
        """Test case for api_tasks_id_get

        Returns one task  # noqa: E501
        """
        pass

    def test_api_tasks_id_log_patch(self):
        """Test case for api_tasks_id_log_patch

        Logs work for a task record  # noqa: E501
        """
        pass

    def test_api_tasks_id_patch(self):
        """Test case for api_tasks_id_patch

        Update an existing task  # noqa: E501
        """
        pass

    def test_api_tasks_id_reopen_patch(self):
        """Test case for api_tasks_id_reopen_patch

        Reopens a task for the current user  # noqa: E501
        """
        pass

    def test_api_tasks_id_start_patch(self):
        """Test case for api_tasks_id_start_patch

        Start a task record  # noqa: E501
        """
        pass

    def test_api_tasks_id_stop_patch(self):
        """Test case for api_tasks_id_stop_patch

        Stops a task record for the current user  # noqa: E501
        """
        pass

    def test_api_tasks_id_unassign_patch(self):
        """Test case for api_tasks_id_unassign_patch

        Unassign a task from the current user  # noqa: E501
        """
        pass

    def test_api_tasks_post(self):
        """Test case for api_tasks_post

        Creates a new Task  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
