# coding: utf-8

"""
    Kimai - API Docs

    JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json)   # noqa: E501

    OpenAPI spec version: 0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kimai_python
from kimai_python.api.kiosk_api import KioskApi  # noqa: E501
from kimai_python.rest import ApiException


class TestKioskApi(unittest.TestCase):
    """KioskApi unit test stubs"""

    def setUp(self):
        self.api = KioskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_kiosks_get(self):
        """Test case for api_kiosks_get

        Returns a collection of UserAuthCodes objects  # noqa: E501
        """
        pass

    def test_api_kiosks_id_get(self):
        """Test case for api_kiosks_id_get

        Returns one UserAuthCodes entity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
