# coding: utf-8

"""
    Kimai - API Docs

    JSON API for the Kimai time-tracking software: [API documentation](https://www.kimai.org/documentation/rest-api.html), [Swagger definition file](doc.json)   # noqa: E501

    OpenAPI spec version: 0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserCollection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'alias': 'str',
        'username': 'str',
        'account_number': 'str',
        'enabled': 'bool',
        'color': 'str'
    }

    attribute_map = {
        'id': 'id',
        'alias': 'alias',
        'username': 'username',
        'account_number': 'accountNumber',
        'enabled': 'enabled',
        'color': 'color'
    }

    def __init__(self, id=None, alias=None, username=None, account_number=None, enabled=None, color=None):  # noqa: E501
        """UserCollection - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._alias = None
        self._username = None
        self._account_number = None
        self._enabled = None
        self._color = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if alias is not None:
            self.alias = alias
        self.username = username
        if account_number is not None:
            self.account_number = account_number
        if enabled is not None:
            self.enabled = enabled
        if color is not None:
            self.color = color

    @property
    def id(self):
        """Gets the id of this UserCollection.  # noqa: E501


        :return: The id of this UserCollection.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserCollection.


        :param id: The id of this UserCollection.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def alias(self):
        """Gets the alias of this UserCollection.  # noqa: E501


        :return: The alias of this UserCollection.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this UserCollection.


        :param alias: The alias of this UserCollection.  # noqa: E501
        :type: str
        """

        self._alias = alias

    @property
    def username(self):
        """Gets the username of this UserCollection.  # noqa: E501


        :return: The username of this UserCollection.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserCollection.


        :param username: The username of this UserCollection.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def account_number(self):
        """Gets the account_number of this UserCollection.  # noqa: E501


        :return: The account_number of this UserCollection.  # noqa: E501
        :rtype: str
        """
        return self._account_number

    @account_number.setter
    def account_number(self, account_number):
        """Sets the account_number of this UserCollection.


        :param account_number: The account_number of this UserCollection.  # noqa: E501
        :type: str
        """

        self._account_number = account_number

    @property
    def enabled(self):
        """Gets the enabled of this UserCollection.  # noqa: E501


        :return: The enabled of this UserCollection.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this UserCollection.


        :param enabled: The enabled of this UserCollection.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def color(self):
        """Gets the color of this UserCollection.  # noqa: E501


        :return: The color of this UserCollection.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this UserCollection.


        :param color: The color of this UserCollection.  # noqa: E501
        :type: str
        """

        self._color = color

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserCollection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserCollection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
